// Mocks generated by Mockito 5.0.10 from annotations
// in dicoding_flutter_fundamental/test/api/api_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:dicoding_flutter_fundamental/api/api_service.dart' as _i6;
import 'package:dicoding_flutter_fundamental/data/model/customer_review_result.dart'
    as _i5;
import 'package:dicoding_flutter_fundamental/data/model/restaurant_detail_result.dart'
    as _i3;
import 'package:dicoding_flutter_fundamental/data/model/restaurant_list_result.dart'
    as _i2;
import 'package:dicoding_flutter_fundamental/data/model/restaurant_search_result.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeRestaurantListResult extends _i1.Fake
    implements _i2.RestaurantListResult {}

class _FakeRestaurantDetailResult extends _i1.Fake
    implements _i3.RestaurantDetailResult {}

class _FakeRestaurantSearchResult extends _i1.Fake
    implements _i4.RestaurantSearchResult {}

class _FakeCustomerReviewResult extends _i1.Fake
    implements _i5.CustomerReviewResult {}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i6.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.RestaurantListResult> getRestaurantList() =>
      (super.noSuchMethod(Invocation.method(#getRestaurantList, []),
              returnValue: Future<_i2.RestaurantListResult>.value(
                  _FakeRestaurantListResult()))
          as _i7.Future<_i2.RestaurantListResult>);
  @override
  _i7.Future<_i3.RestaurantDetailResult> getRestaurantDetail(String? id) =>
      (super.noSuchMethod(Invocation.method(#getRestaurantDetail, [id]),
              returnValue: Future<_i3.RestaurantDetailResult>.value(
                  _FakeRestaurantDetailResult()))
          as _i7.Future<_i3.RestaurantDetailResult>);
  @override
  _i7.Future<_i4.RestaurantSearchResult> searchRestaurant(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchRestaurant, [query]),
              returnValue: Future<_i4.RestaurantSearchResult>.value(
                  _FakeRestaurantSearchResult()))
          as _i7.Future<_i4.RestaurantSearchResult>);
  @override
  _i7.Future<_i5.CustomerReviewResult> postReview(
          String? name, String? review, String? id) =>
      (super.noSuchMethod(Invocation.method(#postReview, [name, review, id]),
              returnValue: Future<_i5.CustomerReviewResult>.value(
                  _FakeCustomerReviewResult()))
          as _i7.Future<_i5.CustomerReviewResult>);
}
